baseURL = "https://postflight.org/"
languageCode = "en-us"
title = "Postflight"

disableKinds = ["taxonomy", "term", "RSS"]
theme = "postflight-showcase"

[params]
  subtitle = "An online EASA AMC1 FCL.050 private pilot flight log"