baseURL = "https://postflight.org/"
languageCode = "en-us"
title = "Postflight"

disableKinds = ["taxonomy", "term", "RSS"]

[frontmatter]
  lastmod = [':git', 'lastmod', ':fileModTime', ':default']

[params]
  subtitle = "An online EASA AMC1 FCL.050 private pilot flight log"
  demo = "https://demo.postflight.org"
  [params.github]
  org = "https://github.com/postflight-org"
  people = "https://github.com/orgs/postflight-org/people"